export enum MediaType {
  MANGA = 'manga',
  NOVEL = 'novel',
  LIGHTNOVEL = 'lightnovel',
  ONESHOT = 'oneshot',
  DOUJIN = 'doujin',
  MANHWA = 'manhwa',
  MANHUA = 'manhua',
}

export enum OrderBy {
  TITLE = 'title',
  START_DATE = 'start_date',
  END_DATE = 'end_date',
  CHAPTERS = 'chapters',
  VOLUMES = 'volumes',
  SCORE = 'score',
  RANK = 'rank',
  POPULARITY = 'popularity',
  FAVORITES = 'favorites',
}

export enum SortOrder {
  ASC = 'asc',
  DESC = 'desc',
}

export enum Status {
  PUBLISHING = 'publishing',
  COMPLETE = 'complete',
  HIATUS = 'hiatus',
  DISCONTINUED = 'discontinued',
  UPCOMING = 'upcoming',
}

export enum MangaGenre {
  ADULT_CAST = 50,
  ANTHROPOMORPHIC = 51,
  CGDCT = 52,
  CHILDCARE = 53,
  COMBAT_SPORTS = 54,
  CROSSDRESSING = 44,
  DELINQUENTS = 55,
  DETECTIVE = 39,
  EDUCATIONAL = 56,
  GAG_HUMOR = 57,
  GORE = 58,
  HAREM = 35,
  HIGH_STAKES_GAME = 59,
  HISTORICAL = 13,
  IDOLS_FEMALE = 60,
  IDOLS_MALE = 61,
  ISEKAI = 62,
  IYASHIKEI = 63,
  LOVE_POLYGON = 64,
  MAGICAL_SEX_SHIFT = 65,
  MAHOU_SHOUJO = 66,
  MARTIAL_ARTS = 17,
  MECHA = 18,
  MEDICAL = 67,
  MEMOIR = 68,
  MILITARY = 38,
  MUSIC = 19,
  MYTHOLOGY = 6,
  ORGANIZED_CRIME = 69,
  OTAKU_CULTURE = 70,
  PARODY = 20,
  PERFORMING_ARTS = 71,
  PETS = 72,
  PSYCHOLOGICAL = 40,
  RACING = 3,
  REINCARNATION = 73,
  REVERSE_HAREM = 74,
  LOVE_STATUS_QUO = 75,
  SAMURAI = 21,
  SCHOOL = 23,
  SHOWBIZ = 76,
  SPACE = 29,
  STRATEGY_GAME = 11,
  SUPER_POWER = 31,
  SURVIVAL = 77,
  TEAM_SPORTS = 78,
  TIME_TRAVEL = 79,
  VAMPIRE = 32,
  VIDEO_GAME = 80,
  VILLAINESS = 81,
  VISUAL_ARTS = 82,
  WORKPLACE = 48,
  URBAN_FANTASY = 83,
  ECCHI = 9,
  EROTICA = 49,
  HENTAI = 12,
}
